### ISSUE TITLE
サンプルモデルを利用しようとしたらエラー

### ISSUE THREAD

**Issue by kpis-msa** [Drunkar/japanese_talk_api_transformer#1]
サンプルモデルを利用しようとしたら、次のエラーが出ました。

$ curl localhost:5000?input=hello%20men
curl: (7) Failed to connect to localhost port 5000: Connection refused

どうやら5000番ポートが拒否されたようです。
どうしたら5000番ポートに接続できるようになりますか。
よろしくお願いします。

**Comment by Drunkar** [comment]
- docker ps等でquery-serverコンテナが正常に動いていることを確認してください
- ufw等のファイアウォールで5000ポートを許可してください

**Comment by kpis-msa** [comment]
まず、docker psの結果です。

$ docker ps
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
128f28bfd73e        japanesetalkapitransformer_query-server   "bash -c 't2t-query-…"   8 seconds ago       Up 8 seconds        0.0.0.0:5000->5000/tcp   japanesetalkapitransformer_query-server_1
e799ddfdd399        tensorflow/serving:1.12.0                 "/usr/bin/tf_serving…"   8 seconds ago       Up 8 seconds        8500-8501/tcp            japanesetalkapitransformer_model-server_1

次に、ufwの状態です。

$ sudo ufw status numbered
Status: active

     To                         Action      From
     --                         ------      ----
[ 1] 5000/tcp                   ALLOW IN    Anywhere                  
[ 2] 5000/tcp (v6)              ALLOW IN    Anywhere (v6)  

最後にcurlコマンドです。

$ curl localhost:5000?input=hello%20men
curl: (7) Failed to connect to localhost port 5000: Connection refused

いかがでしょうか。
よろしくお願いします。

**Comment by Drunkar** [comment]
問題なさそうに見えますね。。。
`docker-compose logs query-server `
の結果をお教えいただけますでしょうか。また、お使いのOSはどちらでしょうか。

`curl localhost:5000?input=hello%20men` の代わりに、`curl 127.0.0.1:5000?input=hello%20men` を試すと結果が違ってくるかもしれません。

**Comment by kpis-msa** [comment]
まずはlogsです。

$ docker-compose logs query-server
Attaching to japanesetalkapitransformer_query-server_1
query-server_1  |   File "/app/t2t-usr/__init__.py", line 1, in <module>
query-server_1  |     from . import conversation_ja
query-server_1  |   File "/app/t2t-usr/conversation_ja.py", line 7, in <module>
query-server_1  |     from tensor2tensor.models import transformer
query-server_1  |   File "/usr/local/lib/python3.6/site-packages/tensor2tensor/models/__init__.py", line 29, in <module>
query-server_1  |     from tensor2tensor.models import mtf_image_transformer
query-server_1  |   File "/usr/local/lib/python3.6/site-packages/tensor2tensor/models/mtf_image_transformer.py", line 29, in <module>
query-server_1  |     import mesh_tensorflow as mtf
query-server_1  |   File "/usr/local/lib/python3.6/site-packages/mesh_tensorflow/__init__.py", line 22, in <module>
query-server_1  |     from mesh_tensorflow import beam_search
query-server_1  |   File "/usr/local/lib/python3.6/site-packages/mesh_tensorflow/beam_search.py", line 23, in <module>
query-server_1  |     from mesh_tensorflow import ops_with_redefined_builtins as mtf
query-server_1  |   File "/usr/local/lib/python3.6/site-packages/mesh_tensorflow/ops_with_redefined_builtins.py", line 22, in <module>
query-server_1  |     from mesh_tensorflow.ops import *  # pylint: disable=wildcard-import
query-server_1  |   File "/usr/local/lib/python3.6/site-packages/mesh_tensorflow/ops.py", line 29, in <module>
query-server_1  |     from mesh_tensorflow import utils
query-server_1  |   File "/usr/local/lib/python3.6/site-packages/mesh_tensorflow/utils.py", line 25, in <module>
query-server_1  |     import tensorflow.compat.v1 as tf
query-server_1  | ModuleNotFoundError: No module named 'tensorflow.compat.v1'

次は、unameです。


$ uname -a
Linux ip-172-31-8-221 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

最後は、curlです。

$ curl 127.0.0.1:5000?input=hello%20men
curl: (7) Failed to connect to 127.0.0.1 port 5000: Connection refused

よろしくお願いします。

**Comment by kpis-msa** [comment]
追伸ですが、build時に次のエラーメッセージがありました。

ERROR: tensorflow-serving-api 2.3.0 has requirement tensorflow<3,>=2.3, but you'll have tensorflow 1.12.0 which is incompatible.

**Comment by Drunkar** [comment]
ありがとうございます。tensor2tensorの依存パッケージが最新のものを使うようになっているので互換性エラーが起きているようです。常に最新のものを見るようにしているとは盲点でした。。。
https://github.com/Drunkar/tensor2tensor-optuna/tree/v1.10.0-query-server-flask
こちらのsetup.pyを修正して動くようにします。

何らかの進捗があればこのスレッドでご報告します。

**Comment by Drunkar** [comment]
該当のリポジトリを修正しました。
japanese_talk_api_transformer ディレクトリで以下を順番に実行すれば今度は動くと思います。

```
docker-compose down
docker-compose build --no-cache
docker-compose up -d
curl localhost:5000?input=hello%20men
```

**Comment by kpis-msa** [comment]
ありがとうございます。実行することができました。
実行結果は次の通りです。

$ curl localhost:5000?input=hello%20men
{"outputs":[{"score":[-3.765416145324707,-5.39048433303833,-6.801329135894775,-8.260896682739258,-9.064001083374023],"val":["","","\u3002","","\u3002"]}]}

ところで、出力結果の["","","\u3002","","\u3002"]はどういう意味でしょうか。
よろしくお願いします。

**Comment by Drunkar** [comment]
良かったです！
\u3002 は 。 ですね。つまり返答は、
- 第一候補:  空文字
- 第二候補:  空文字
- 第三候補:  。
- 第四候補:  空文字
- 第五候補:  。

ということです。サンプルモデルは学習の初期段階なのではっきり言ってでたらめで使い物になりません。動作検証をしていただくためのものです。
学習済みのモデルは[gumroad](https://gumroad.com/l/japanese_talk_api_transformer)にて販売しておりますので、ちゃんとした返答を得たい場合はそちらをご検討ください。
参考までに、学習済みモデルを使った場合、返答例は以下のようになります:
![image](https://user-images.githubusercontent.com/1223433/95409383-7173fc80-095c-11eb-9ff6-ce4c7344105c.png)

※hubotプラグイン( https://github.com/Drunkar/hubot-japanese-talk-transformer )を使ってslack botに返答させています。

解決いただけたようですので、いったんこのissueはcloseとさせていただきます。(close後もコメントすることは可能です。)
